version: '3.7'

services:

  client:
    container_name: client
    build:
      context: ./src/client
      dockerfile: ../../docker/Dockerfile
    working_dir: /app/src/client
    command: npm start
    volumes:
      - '.:/app'
    ports:
      - 3000:3000

  server:
    container_name: server
    build:
      context: ./src/server
      dockerfile: ../../docker/Dockerfile
    working_dir: /app/src/server
    command: npm start
    volumes:
    - '.:/app'

    ports:
      - 9000:9000

