version: '2.2'

services:
  postgres:
    image: "postgres"
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data/ 

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - '.:/app/'
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db:
