version: '3.7'

services:

  client:
    stdin_open: true
    container_name: client
    build:
      context: ./src/client
      dockerfile: ../../docker/Dockerfile
    volumes:
      - './src/client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true


  server:
    container_name: server
    build:
      context: ./src/server
      dockerfile: ../../docker/Dockerfile
    command: npm start
    volumes:
      - './src/server:/app'
      - '/app/node_modules'
    ports:
      - 9000:9000

